# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test suite

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        fetch-tags: true
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.PRIVATE_SSH_KEY }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install 'fftarray[dev] @ git+ssh://git@github.com/QSTheory/fftarray.git'
        python -m pip install -e ".[dev]"
    - name: Test with mypy
      run: |
        mypy matterwave
    - name: Test with pytest
      run: |
        python -m pytest
