name: Run minimal pytest via pixi
# This is only a minimal config to use less CI resources.

on:
  pull_request:

permissions:
  contents: read

jobs:
  test-minimal:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [check313]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.PRIVATE_SSH_KEY }}
    - name: Write SSH private key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PRIVATE_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
    - name: Add GitHub to known_hosts
      run: ssh-keyscan github.com >> ~/.ssh/known_hosts
    - name: Configure SSH
      run: |
        echo "Host github.com" > ~/.ssh/config
        echo "    HostName github.com" >> ~/.ssh/config
        echo "    User git" >> ~/.ssh/config
        echo "    IdentityFile ~/.ssh/id_ed25519" >> ~/.ssh/config
        chmod 600 ~/.ssh/config
    - uses: prefix-dev/setup-pixi@v0.8.1
      with:
        pixi-version: v0.40.3
        environments: ${{ matrix.environment }}
        cache: true
    # Here we do not split mypy and test into a matrix to save resources.
    - run: pixi run -e ${{ matrix.environment }} check
      # Can be removed when fftarray can be installed via pip:
      env:
        GIT_LFS_SKIP_SMUDGE: 1
