name: Run minimal pytest via pixi
# This is only a minimal config to use less CI resources.

on:
  pull_request:

permissions:
  contents: read

jobs:
  test-minimal:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [check313]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.PRIVATE_SSH_KEY }}
    - name: Add GitHub to known_hosts
      run: ssh-keyscan github.com >> ~/.ssh/known_hosts
    - name: Verify SSH access
      run: ssh -T git@github.com || true
    - name: Debug SSH Configuration
      run: |
        echo "SSH Key is loaded:"
        ssh-add -l
        echo "Known hosts:"
        cat ~/.ssh/known_hosts
        export GIT_SSH_COMMAND="ssh -v"
    - uses: prefix-dev/setup-pixi@v0.8.1
      with:
        pixi-version: v0.40.3
        environments: ${{ matrix.environment }}
        cache: true
    # Here we do not split mypy and test into a matrix to save resources.
    - run: pixi run -e ${{ matrix.environment }} check
