name: Run full matrix pytest via pixi

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test-full:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [check310, check311, check312, check313, checknumpy125]
        command: [ruff_all, mypy, test_all]
        # An option to run with multiple CI runners, currently saves 20s,
        # not worth the increased CI minutes usage.
        # command: [mypy, test_all_group 1, test_all_group 2]
    # env:
    #   N_GROUPS: 2
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - uses: prefix-dev/setup-pixi@v0.8.1
      with:
        pixi-version: v0.39.5
        environments: ${{ matrix.environment }}
        cache: true
    - run: pixi run -e ${{ matrix.environment }} ${{ matrix.command }}
